# Generated by Django 4.2.11 on 2024-04-23 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0)),
                ('name', models.CharField(default='Discussion', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Facilitator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(default='username', max_length=100, unique=True)),
            ],
            options={
                'permissions': (('can_create_groups', 'Create Groups'),),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Group', max_length=100)),
                ('size', models.IntegerField(default=0)),
                ('facilitator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discussion.facilitator')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discussion.group')),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Enter a prompt for the discussion', max_length=1000)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discussion.facilitator')),
                ('discussion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discussion.discussion')),
            ],
        ),
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Enter a response', max_length=1000)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discussion.participant')),
                ('prompt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='discussion.prompt')),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('prompt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discussion.prompt')),
            ],
        ),
        migrations.CreateModel(
            name='DistributedThought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discussion.participant')),
                ('distribution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discussion.distribution')),
                ('thought', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discussion.thought')),
            ],
        ),
        migrations.AddField(
            model_name='discussion',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discussion.group'),
        ),
    ]
