# Generated by Django 4.2.11 on 2024-04-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
