# Generated by Django 4.2.11 on 2024-04-28 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_alter_distribution_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributedthought',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer', to='discussion.thought'),
        ),
        migrations.AlterField(
            model_name='distributedthought',
            name='thought',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thought', to='discussion.thought'),
        ),
    ]
