# Generated by Django 4.2.11 on 2024-03-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='title',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='date',
        ),
    ]
