# Generated by Django 4.2.11 on 2024-04-05 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_rename_title_discussion_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributedThought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discussion.group')),
            ],
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Enter a the prompt of the discussion', max_length=1000)),
                ('author', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Enter a response', max_length=1000)),
                ('prompt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discussion.prompt')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='facilitator',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='prompt',
        ),
        migrations.AddField(
            model_name='facilitator',
            name='discussions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='discussion.discussion'),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='username',
            field=models.CharField(default='username', max_length=100),
        ),
        migrations.AddField(
            model_name='prompt',
            name='discussion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discussion.discussion'),
        ),
        migrations.AddField(
            model_name='group',
            name='facilitator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discussion.facilitator'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='prompt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discussion.prompt'),
        ),
        migrations.AddField(
            model_name='distributedthought',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discussion.participant'),
        ),
        migrations.AddField(
            model_name='distributedthought',
            name='distribution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discussion.distribution'),
        ),
        migrations.AddField(
            model_name='distributedthought',
            name='thought',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discussion.thought'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discussion.group'),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='prompt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discussion.prompt'),
        ),
    ]
