# Generated by Django 4.2.11 on 2024-04-05 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0003_distributedthought_distribution_group_participant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitator',
            name='discussions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discussion.discussion'),
        ),
        migrations.AlterField(
            model_name='facilitator',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='facilitator',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='facilitator',
            name='username',
            field=models.CharField(default='username', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='thought',
            name='prompt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='discussion.prompt'),
        ),
    ]
