# Generated by Django 4.2.11 on 2024-04-05 18:27

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0004_alter_facilitator_discussions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default=django.db.models.fields.AutoField, max_length=100),
        ),
        migrations.AddField(
            model_name='group',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
