# Generated by Django 4.2.11 on 2024-04-06 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0005_group_name_group_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilitator',
            options={'permissions': (('can_create_groups', 'Create Groups'),)},
        ),
        migrations.AlterField(
            model_name='facilitator',
            name='discussions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discussion.discussion'),
        ),
        migrations.AlterField(
            model_name='facilitator',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='facilitator',
            name='prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discussion.prompt'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(default='Group', max_length=100),
        ),
    ]
