# Generated by Django 4.2.11 on 2024-04-09 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0006_alter_facilitator_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilitator',
            name='prompt',
        ),
        migrations.AddField(
            model_name='prompt',
            name='facilitator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discussion.facilitator'),
        ),
    ]
