# Generated by Django 4.2.11 on 2024-04-09 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0007_remove_facilitator_prompt_prompt_facilitator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='facilitator',
        ),
        migrations.AlterField(
            model_name='prompt',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discussion.facilitator'),
        ),
    ]
