# Generated by Django 4.2.11 on 2024-04-09 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0008_remove_prompt_facilitator_alter_prompt_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='content',
            field=models.TextField(help_text='Enter a prompt for the discussion', max_length=1000),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='discussion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discussion.discussion'),
        ),
    ]
