# Generated by Django 4.2.11 on 2024-04-09 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0009_alter_prompt_content_alter_prompt_discussion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilitator',
            name='discussions',
        ),
    ]
