# Generated by Django 5.0.2 on 2024-04-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0011_thought_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
