# Generated by Django 4.2.11 on 2024-04-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0013_discussion_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='access',
        ),
        migrations.AddField(
            model_name='discussion',
            name='name',
            field=models.CharField(default='Discussion', max_length=200),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
